import { describe, it, expect, afterEach, mock } from 'bun:test';
import React from 'react';
import { render, screen, cleanup } from '@testing-library/react';
import { GlobalRegistrator } from '@happy-dom/global-registrator';
import { DialogueBox } from '../DialogueBox.jsx';

GlobalRegistrator.register();

describe('DialogueBox', () => {
  afterEach(() => {
    cleanup();
  });

  it('renders standard text without typing', () => {
    render(<DialogueBox text="Hello world" mood="😊" charName="Alice" />);
    const textElement = document.body.textContent;
    expect(textElement).toContain('Hello world');
    expect(textElement).toContain('😊');
  });

  it('renders character name and description', () => {
    render(<DialogueBox text="Hello" charName="Alice" charDesc="A test character" />);
    const textElement = document.body.textContent;
    expect(textElement).toContain('Alice');
    expect(textElement).toContain('(A test character)');
  });

  it('renders player styling correctly', () => {
    const { container } = render(<DialogueBox text="Hello" isPlayer={true} charName="Player" />);

    const box = container.firstChild;
    expect(box.className).toContain('bg-slate-900/95');
    expect(box.className).toContain('border-blue-500');

    expect(document.body.textContent).not.toContain('(');
  });

  it('renders NPC styling correctly', () => {
    const { container } = render(<DialogueBox text="Hello" isPlayer={false} charName="NPC" />);

    const box = container.firstChild;
    expect(box.className).toContain('bg-[#2c241b]/95');
    expect(box.className).toContain('border-amber-600');
  });

  it('renders the Typewriter component when isTyping is true', () => {
    const onCompleteMock = mock(() => {});
    const { container } = render(<DialogueBox text="Typing text..." isTyping={true} onComplete={onCompleteMock} />);
    // Typewriter handles the text output. If isTyping is true, the raw text shouldn't just be output directly through dangerouslySetInnerHTML immediately.
    // Given the simple Typewriter implementation, the full text won't be in the body text content right away.
    expect(document.body.textContent).not.toContain('Typing text...');
  });

  it('formats and sanitizes text properly', () => {
    const maliciousText = "**bold** <script>alert(1)</script>";
    render(<DialogueBox text={maliciousText} isTyping={false} />);
    const html = document.body.innerHTML;
    // Check it formats bold
    expect(html).toContain('<b>bold</b>');
    // Check it sanitizes script
    expect(html).not.toContain('<script>alert(1)</script>');
  });

  it('handles falsy or missing text', () => {
    render(<DialogueBox text={null} isTyping={false} />);
    const html = document.body.innerHTML;
    expect(html).toContain('<span></span>'); // Empty span generated by DOMPurify/formatText for empty string
  });
});
